title: File Manager
email: hacdias@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  File Manager is a stylish and elegant web file manager you can use
  as your own cloud or integrate on your own applications.
baseurl: "/filemanager" # the subpath of your site, e.g. /blog
url: "https://henriquedias.com"
twitter_username: hacdias
github_username:  hacdias
google_analytics: UA-59697241-1
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true

docs:
  - title: Documentation
    links:
      - page: Quick Start
        url: /quick-start/
      - page: Installation
        url: /installation/
        links:
          - page: One-step Script
            url: /installation/#one-step-script
          - page: Caddy
            url: /installation/#caddy
          - page: Docker
            url: /installation/#docker
      - page: Configuration
        url: /configuration/